# Connect Cluster Einstellungen
bootstrap.servers=kafka:29092
rest.port=8083
rest.advertised.host.name=connect

# Connect Cluster Settings
group.id=local-msk-connect-group
config.storage.topic=docker-connect-configs
offset.storage.topic=docker-connect-offsets
status.storage.topic=docker-connect-status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

# Default Converters (Reines JSON, ohne Schema Registry)
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false

# EnvVar Provider für die SolExperts Credentials aktivieren
config.providers=env
config.providers.env.class=org.apache.kafka.common.config.provider.EnvVarConfigProvider

# Standard Plugin Pfad im Apache Image (hier liegt MirrorMaker 2)
plugin.path=/opt/kafka/libs