sonar.organization=swisstopo
sonar.projectKey=swisstopo_lg-monteis
sonar.projectName=lg-monteis

# This disables the rule which marks TODOs as issues
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S1135
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java

# suppress rule for missing label/id as this is a false positive for material components
sonar.issue.ignore.multicriteria.e2.ruleKey=Web:S6853
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.html

# suppress "should be readonly" rule: as it creates just noise
sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S2933
sonar.issue.ignore.multicriteria.e3.resourceKey=webapp/src/**/*.ts

sonar.coverage.exclusions=\
  core/src/test/**/*,\
  pipeline/src/test/**/*,\
  webapp/src/app/**/*,\
  **/*Application.java, **/*Config.java,\
  **/dto/**, **/model/**,\

sonar.sources=webapp/src/app, core/src/main/java, pipeline/src/main/java
sonar.tests=webapp/src/app, core/src/test/java, pipeline/src/test/java
sonar.test.inclusions = webapp/src/app/**/*.spec.ts, core/src/test/java/**/*.java, pipeline/src/test/java/**/*.java
