sonar.organization=swisstopo
sonar.projectKey=swisstopo_lg-monteis
sonar.projectName=lg-monteis

# This disables the rule which marks TODOs as issues
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S1135
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java

sonar.coverage.exclusions=\
  core/src/test/**/*,\
  pipeline/src/test/**/*,\
  webapp/src/app/**/*,\
  **/*Application.java, **/*Config.java,\
  **/dto/**, **/model/**,\

sonar.sources=webapp/src/app, core/src/main/java, pipeline/src/main/java
sonar.tests=webapp/src/app, core/src/test/java, pipeline/src/test/java
sonar.test.inclusions = webapp/src/app/**/*.spec.ts, core/src/test/java/**/*.java, pipeline/src/test/java/**/*.java
