-- -----------------------------------------------------------------------------
-- Row-Level Security (MON-111)
--
-- Read authorization is enforced by PostgreSQL. For each transaction the
-- application propagates whether the caller can read every row (from the
-- api:read-all authority) and their visible experiment IDs into transaction-local
-- GUCs. The helper functions below expose that context to RLS policies and
-- security views.
-- -----------------------------------------------------------------------------

CREATE FUNCTION can_read_all() RETURNS boolean AS $$
    SELECT current_setting('app.read_all', true) = 'true'
$$ LANGUAGE sql STABLE;

CREATE FUNCTION current_experiment_ids() RETURNS bigint[] AS $$
    SELECT COALESCE(
        string_to_array(current_setting('app.user_experiment_ids', true), ',')::bigint[],
        ARRAY[]::bigint[]
    )
$$ LANGUAGE sql STABLE;

-- Shared access predicates reused by RLS policies and security views.
CREATE FUNCTION can_access_experiment(target_experiment_id bigint) RETURNS boolean AS $$
    SELECT can_read_all() OR target_experiment_id = ANY (current_experiment_ids())
$$ LANGUAGE sql STABLE;

CREATE FUNCTION can_access_sensor(target_sensor_id bigint) RETURNS boolean AS $$
    SELECT can_read_all() OR EXISTS (
        SELECT 1 FROM experiment_sensor es
        WHERE es.sensor_id = target_sensor_id
          AND es.experiment_id = ANY (current_experiment_ids())
    )
$$ LANGUAGE sql STABLE;

-- -----------------------------------------------------------------------------
-- Native RLS for local tables.
--
-- Reads are filtered by experiment membership. Writes remain unrestricted
-- because all database access uses the shared application role (core_app);
-- command authorization is enforced in the application layer.
-- -----------------------------------------------------------------------------
ALTER TABLE sensors ENABLE ROW LEVEL SECURITY;
CREATE POLICY sensors_read ON sensors FOR SELECT
    USING (can_access_sensor(sensors.id));
CREATE POLICY sensors_insert ON sensors FOR INSERT WITH CHECK (true);
CREATE POLICY sensors_update ON sensors FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY sensors_delete ON sensors FOR DELETE USING (true);

ALTER TABLE experiments ENABLE ROW LEVEL SECURITY;
-- Experiments are checked directly by ID so experiments without sensors remain
-- visible to authorized users.
CREATE POLICY experiments_read ON experiments FOR SELECT
    USING (can_access_experiment(experiments.id));
CREATE POLICY experiments_insert ON experiments FOR INSERT WITH CHECK (true);
CREATE POLICY experiments_update ON experiments FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY experiments_delete ON experiments FOR DELETE USING (true);

-- -----------------------------------------------------------------------------
-- raw_sensor_reading is a FOREIGN TABLE and therefore cannot use native RLS.
-- These views provide equivalent filtering. The application must query a view
-- instead of the foreign table.
--
-- The restriction is a plain join against sensors: RLS on sensors (policy
-- sensors_read above) is what actually filters, and security_invoker keeps that
-- policy evaluated as the calling user. sensors.code is UNIQUE (V2), so the join
-- cannot duplicate reading rows.
--
-- Two things about this shape are load-bearing for performance. Both were
--
-- 1. NO security_barrier. A security-barrier view is never flattened into the
--    parent query, so the caller's ORDER BY cannot become pathkeys on the foreign
--    scan. With it, the remote query went out with no ORDER BY and no filter at
--    all, and Postgres pulled all 525,605 rows across the FDW to return 100:
--      security_barrier:    794 ms
--      without:              57 ms
--    The trade-off is that a non-leakproof qual supplied by the caller could in
--    principle be evaluated before the join and observe a row for a sensor the
--    caller cannot see. Every query against these views is generated by jOOQ from
--    built-in, leakproof operators, so there is nothing to exploit. If ad-hoc or
--    user-defined predicates are ever allowed here, restore security_barrier and
--    accept the pushdown loss, or filter in the application with a bound
--    sensor-code parameter instead.
--
-- 2. A JOIN, not a function call. Replacing the join with a STABLE function
--    returning the accessible codes (sensor_id = ANY (accessible_codes())) is far
--    worse: PostgreSQL does not cache STABLE results across rows and the qual is
--    not shippable to the FDW, so it becomes a local filter evaluated once per
--    row. A 52k-row range scan took 2,800 ms that way versus 65 ms with the join.
--    It only looks acceptable on LIMIT queries because they stop early.
-- -----------------------------------------------------------------------------
CREATE VIEW sensor_reading_secured WITH (security_invoker = true) AS
SELECT r.*
FROM raw_sensor_reading r
JOIN sensors s ON s.code = r.sensor_id;

GRANT SELECT ON sensor_reading_secured TO core_app;
