-- -----------------------------------------------------------------------------
-- Migrate all application primary keys (and derived foreign keys) of the
-- Metadaten-DB from BIGSERIAL/BIGINT to UUIDv7, generated by PostgreSQL 18's
-- built-in uuidv7().
--
-- This migration is designed to be safe to run against tables that already
-- contain data (e.g. production): it never TRUNCATEs or deletes rows. Every
-- existing row gets a freshly generated UUIDv7 value via a column default
-- (which, being volatile, forces a full rewrite and evaluates once per row),
-- foreign keys are backfilled by joining the old bigint ids to the new UUIDs,
-- and only then are the old bigint columns dropped in favor of the new ones.
--
-- Out of scope: Javers audit tables (jv_global_id, jv_commit,
-- jv_commit_property, jv_snapshot) and flyway_schema_history. Both are
-- library/tool-owned schemas, not application PKs.
-- -----------------------------------------------------------------------------

-- =============================================================================
-- 1. Add new UUID surrogate columns to every PK-bearing table.
-- =============================================================================
ALTER TABLE formulas ADD COLUMN id_new UUID NOT NULL DEFAULT uuidv7();
ALTER TABLE sensor_types ADD COLUMN id_new UUID NOT NULL DEFAULT uuidv7();
ALTER TABLE sensors ADD COLUMN id_new UUID NOT NULL DEFAULT uuidv7();
ALTER TABLE experiments ADD COLUMN id_new UUID NOT NULL DEFAULT uuidv7();

-- =============================================================================
-- 2. Add and backfill new UUID foreign-key columns.
-- =============================================================================
ALTER TABLE sensors ADD COLUMN type_id_new UUID;
ALTER TABLE sensors ADD COLUMN formula_id_new UUID;

UPDATE sensors s
SET type_id_new = st.id_new
FROM sensor_types st
WHERE s.type_id = st.id;

UPDATE sensors s
SET formula_id_new = f.id_new
FROM formulas f
WHERE s.formula_id = f.id;

ALTER TABLE sensors ALTER COLUMN type_id_new SET NOT NULL;
ALTER TABLE sensors ALTER COLUMN formula_id_new SET NOT NULL;

ALTER TABLE experiment_sensor ADD COLUMN experiment_id_new UUID;
ALTER TABLE experiment_sensor ADD COLUMN sensor_id_new UUID;

UPDATE experiment_sensor es
SET experiment_id_new = e.id_new
FROM experiments e
WHERE es.experiment_id = e.id;

UPDATE experiment_sensor es
SET sensor_id_new = s.id_new
FROM sensors s
WHERE es.sensor_id = s.id;

ALTER TABLE experiment_sensor ALTER COLUMN experiment_id_new SET NOT NULL;
ALTER TABLE experiment_sensor ALTER COLUMN sensor_id_new SET NOT NULL;

-- =============================================================================
-- 3. Drop RLS policies that depend on the bigint-typed access-check functions,
--    so the functions and the columns/constraints they touch can be dropped.
-- =============================================================================
DROP POLICY sensors_read ON sensors;
DROP POLICY sensors_insert ON sensors;
DROP POLICY sensors_update ON sensors;
DROP POLICY sensors_delete ON sensors;

DROP POLICY experiments_read ON experiments;
DROP POLICY experiments_insert ON experiments;
DROP POLICY experiments_update ON experiments;
DROP POLICY experiments_delete ON experiments;

DROP FUNCTION can_access_sensor(bigint);
DROP FUNCTION can_access_experiment(bigint);
DROP FUNCTION current_experiment_ids();

-- =============================================================================
-- 4. Drop old FK constraints, then old PK constraints, then the old bigint
--    columns (this also drops their owned BIGSERIAL sequences), then rename
--    the new UUID columns into place.
-- =============================================================================
ALTER TABLE sensors DROP CONSTRAINT sensors_type_id_fkey;
ALTER TABLE sensors DROP CONSTRAINT sensors_formula_id_fkey;
ALTER TABLE experiment_sensor DROP CONSTRAINT experiment_sensor_experiment_id_fkey;
ALTER TABLE experiment_sensor DROP CONSTRAINT experiment_sensor_sensor_id_fkey;

ALTER TABLE formulas DROP CONSTRAINT formulas_pkey;
ALTER TABLE sensor_types DROP CONSTRAINT sensor_types_pkey;
ALTER TABLE sensors DROP CONSTRAINT sensors_pkey;
ALTER TABLE experiments DROP CONSTRAINT experiments_pkey;
ALTER TABLE experiment_sensor DROP CONSTRAINT experiment_sensor_pkey;

ALTER TABLE experiment_sensor DROP COLUMN experiment_id;
ALTER TABLE experiment_sensor DROP COLUMN sensor_id;
ALTER TABLE sensors DROP COLUMN type_id;
ALTER TABLE sensors DROP COLUMN formula_id;
ALTER TABLE formulas DROP COLUMN id;
ALTER TABLE sensor_types DROP COLUMN id;
ALTER TABLE sensors DROP COLUMN id;
ALTER TABLE experiments DROP COLUMN id;

ALTER TABLE formulas RENAME COLUMN id_new TO id;
ALTER TABLE sensor_types RENAME COLUMN id_new TO id;
ALTER TABLE sensors RENAME COLUMN id_new TO id;
ALTER TABLE sensors RENAME COLUMN type_id_new TO type_id;
ALTER TABLE sensors RENAME COLUMN formula_id_new TO formula_id;
ALTER TABLE experiments RENAME COLUMN id_new TO id;
ALTER TABLE experiment_sensor RENAME COLUMN experiment_id_new TO experiment_id;
ALTER TABLE experiment_sensor RENAME COLUMN sensor_id_new TO sensor_id;

-- =============================================================================
-- 5. Re-add primary keys, foreign keys (with original ON DELETE semantics)
--    and the non-PK indexes that existed before.
-- =============================================================================
ALTER TABLE formulas ADD PRIMARY KEY (id);
ALTER TABLE sensor_types ADD PRIMARY KEY (id);
ALTER TABLE sensors ADD PRIMARY KEY (id);
ALTER TABLE experiments ADD PRIMARY KEY (id);
ALTER TABLE experiment_sensor ADD PRIMARY KEY (experiment_id, sensor_id);

ALTER TABLE sensors ADD CONSTRAINT sensors_type_id_fkey
    FOREIGN KEY (type_id) REFERENCES sensor_types (id) ON DELETE RESTRICT;
ALTER TABLE sensors ADD CONSTRAINT sensors_formula_id_fkey
    FOREIGN KEY (formula_id) REFERENCES formulas (id) ON DELETE RESTRICT;
ALTER TABLE experiment_sensor ADD CONSTRAINT experiment_sensor_experiment_id_fkey
    FOREIGN KEY (experiment_id) REFERENCES experiments (id) ON DELETE CASCADE;
ALTER TABLE experiment_sensor ADD CONSTRAINT experiment_sensor_sensor_id_fkey
    FOREIGN KEY (sensor_id) REFERENCES sensors (id) ON DELETE CASCADE;

CREATE INDEX idx_sensors_formula_id ON sensors (formula_id);
CREATE INDEX experiment_sensor_sensor_id_idx ON experiment_sensor (sensor_id);

-- =============================================================================
-- 6. Recreate the RLS access-check functions against UUID, and the policies
--    that use them.
-- =============================================================================
CREATE FUNCTION current_experiment_ids() RETURNS uuid[] AS $$
    SELECT COALESCE(
        string_to_array(current_setting('app.user_experiment_ids', true), ',')::uuid[],
        ARRAY[]::uuid[]
    )
$$ LANGUAGE sql STABLE;

CREATE FUNCTION can_access_experiment(target_experiment_id uuid) RETURNS boolean AS $$
    SELECT can_read_all() OR target_experiment_id = ANY (current_experiment_ids())
$$ LANGUAGE sql STABLE;

CREATE FUNCTION can_access_sensor(target_sensor_id uuid) RETURNS boolean AS $$
    SELECT can_read_all() OR EXISTS (
        SELECT 1 FROM experiment_sensor es
        WHERE es.sensor_id = target_sensor_id
          AND es.experiment_id = ANY (current_experiment_ids())
    )
$$ LANGUAGE sql STABLE;

CREATE POLICY sensors_read ON sensors FOR SELECT
    USING (can_access_sensor(sensors.id));
CREATE POLICY sensors_insert ON sensors FOR INSERT WITH CHECK (true);
CREATE POLICY sensors_update ON sensors FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY sensors_delete ON sensors FOR DELETE USING (true);

CREATE POLICY experiments_read ON experiments FOR SELECT
    USING (can_access_experiment(experiments.id));
CREATE POLICY experiments_insert ON experiments FOR INSERT WITH CHECK (true);
CREATE POLICY experiments_update ON experiments FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY experiments_delete ON experiments FOR DELETE USING (true);
