name: 'Setup Java and Maven'
description: 'Sets up JDK'
runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        cache: maven
        cache-dependency-path: '**/pom.xml'

    - name: Resolve Maven Dependencies
      shell: bash
      run: mvn dependency:go-offline