services:
  metadata_db:
    container_name: monteis-meta-db
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: monteis-meta
    ports:
      - "5432:5432"
    profiles: [ '', core, db ]
    volumes:
      - ./dataset-meta:/docker-entrypoint-initdb.d

  time_series_db:
    container_name: timescale-db
    image: timescale/timescaledb:latest-pg18
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: monteis-tsdb
    ports:
      - "5433:5432"
    profiles: [ '', core, db ]
    volumes:
      - ./dataset-tsdb:/docker-entrypoint-initdb.d

  kafka:
    image: apache/kafka:4.3.0
    container_name: local-msk-broker
    ports:
      - "9092:9092"
    environment:
      # KRaft specific configuration
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'local-msk-dev-cluster-123'

      # Automatically create topics when a producer writes to them
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

      # Default partitions for newly created topics
      KAFKA_NUM_PARTITIONS: 6

      # How long to retain data (e.g., 7 days in milliseconds)
      KAFKA_LOG_RETENTION_MS: 15766388736

      # Listener configuration (Internal Docker network vs Localhost)
      KAFKA_LISTENERS: 'CONTROLLER://kafka:29093,PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      # Single-node local development settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  connect:
    image: apache/kafka:4.3.0
    container_name: local-msk-connect
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    environment:
      SOLEXPERTS_KAFKA_USERNAME: ${SOLEXPERTS_KAFKA_USERNAME}
      SOLEXPERTS_KAFKA_PASSWORD: ${SOLEXPERTS_KAFKA_PASSWORD}
    volumes:
      - ./connect/connect-distributed.properties:/opt/kafka/config/connect-distributed.properties
    # We override the default command so that the image starts as 'Connect' and not as a 'Broker'
    command: [
      "/opt/kafka/bin/connect-distributed.sh",
      "/opt/kafka/config/connect-distributed.properties"
    ]

  connect-init:
    image: curlimages/curl:8.7.1
    container_name: local-msk-connect-init
    depends_on:
      - connect
    volumes:
      # Mount the file directly to its final destination
      - ./connect/mm2-config.json:/tmp/mm2-config.json
    command: |
      sh -c "
        echo '⏳ Waiting for Kafka Connect REST API to be ready...'
        while ! curl -s http://connect:8083/ > /dev/null; do
          echo 'Waiting 5 more seconds...'
          sleep 5
        done
      
        echo '✅ Kafka Connect is up! Registering MirrorMaker 2 connector...'
        curl -X POST -H 'Content-Type: application/json' -d @/tmp/mm2-config.json http://connect:8083/connectors
      
        echo '\n🎉 Connector registered successfully!'
      "