# application-openapi.properties
# IMPORTANT: This profile is only for generating the open-api definition to use for ts code generation!
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

server.port=9090
# 2. Provide a dummy fast-booting H2 database
spring.datasource.url=jdbc:h2:mem:dummy_openapi;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jooq.sql-dialect=h2

spring.security.oauth2.resourceserver.jwt.issuer-uri=stub
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=stub