# Logging
logging.level.ch.swisstopo.monteis.core=WARN
logging.level.springframework.security=WARN

# Extras
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# DB Configuration (JOOQ)
spring.datasource.url=${CORE_META_DB_JDBC_URL}
spring.datasource.username=${CORE_APP_META_DB_USER}
spring.datasource.password=${CORE_APP_META_DB_PWD}