# Logging
logging.level.ch.swisstopo.monteis.core=WARN
logging.level.springframework.security=WARN

# Server Configuration
server.port=8080

# Extras
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false