# Logging
logging.level.ch.swisstopo.monteis.core=DEBUG
logging.level.springframework.security=DEBUG

# Server Configuration
server.port=8080

# Extras
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true