# Logging
logging.level.ch.swisstopo.monteis.core=DEBUG
logging.level.springframework.security=DEBUG

# Extras
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# DB Configuration (JOOQ)
spring.datasource.url=jdbc:postgresql://localhost:5432/monteis-meta
spring.datasource.username=core_app
spring.datasource.password=pwd_core_app
spring.flyway.enabled=false