# Logging
logging.level.ch.swisstopo.monteis.core=DEBUG
logging.level.springframework.security=DEBUG
logging.level.org.jooq.tools.LoggerListener=DEBUG

# Extras
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Loads global config for DB setup with different users
spring.config.import=optional:file:docker/.env[.properties], optional:file:../docker/.env[.properties]
# DB Configuration (JOOQ)
spring.datasource.url=jdbc:postgresql://localhost:5432/${META_DB_NAME}
spring.datasource.username=${CORE_APP_META_DB_USER}
spring.datasource.password=${CORE_APP_META_DB_PWD}