allowBuilds:
  '@ibm/plex': false
  '@ibm/plex-mono': false
  '@ibm/plex-sans': false
  '@ibm/plex-sans-arabic': false
  '@ibm/plex-sans-devanagari': false
  '@ibm/plex-sans-hebrew': false
  '@ibm/plex-sans-thai': false
  '@ibm/plex-sans-thai-looped': false
  '@ibm/plex-serif': false
  '@nestjs/core': false
  '@openapitools/openapi-generator-cli': false
  '@parcel/watcher': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - '@angular/animations@22.0.3'
  - '@angular/common@22.0.3'
  - '@angular/compiler-cli@22.0.3'
  - '@angular/compiler@22.0.3'
  - '@angular/core@22.0.3'
  - '@angular/forms@22.0.3'
  - '@angular/platform-browser@22.0.3'
  - '@angular/router@22.0.3'
  - prettier@3.8.5
