# Logging
logging.level.ch.swisstopo.monteis.pipeline=DEBUG

# DB Configuration (JOOQ)
spring.datasource.url=jdbc:postgresql://localhost:5433/${app.migration.meta.dbname}
spring.datasource.username=pipeline_app
spring.datasource.password=pwd_pipeline_app

# Flyway config
spring.flyway.enabled=false

app.migration.timescale.dbname=monteis-tsdb
app.migration.timescale.url=jdbc:postgresql://localhost:5433/${app.migration.timescale.dbname}
app.migration.timescale.username=ts_flyway
app.migration.timescale.password=pwd_ts_flyway
app.migration.timescale.locations=classpath:/db/migration/timeseries

# Host must match docker compose service name
app.migration.meta.placeholders.fdw_ts_host=time_series_db
app.migration.meta.placeholders.fdw_ts_port=5433
app.migration.meta.placeholders.fdw_app_user_name=${spring.datasource.username}
app.migration.meta.placeholders.fdw_ts_dbname=${app.migration.timescale.dbname}
app.migration.meta.placeholders.fdw_ts_user=${app.migration.timescale.username}
app.migration.meta.placeholders.fdw_ts_password=${app.migration.timescale.password}