spring.application.name=pipeline

spring.kafka.bootstrap-servers=pkc-7xoy1.eu-central-1.aws.confluent.cloud:9092
spring.kafka.consumer.group-id=swisstopo_1

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.ssl.endpoint.identification.algorithm=https
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${EXTERNAL_KAFKA_USERNAME}" password="${EXTERNAL_KAFKA_PASSWORD}";

# ===================================================================
# Consumer & Offset Management Settings (Prevents Auto-Commits)
# ===================================================================
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual