# Logging
logging.level.ch.swisstopo.monteis.pipeline=DEBUG

# DB Configuration (JOOQ)
# Loads global config for DB setup with different users
spring.config.import=optional:file:docker/.env[.properties], optional:file:../docker/.env[.properties]
# DB Configuration (JOOQ)
spring.datasource.url=jdbc:postgresql://localhost:5433/${TS_DB_NAME}
spring.datasource.username=${PIPELINE_APP_TS_DB_USER}
spring.datasource.password=${PIPELINE_APP_TS_DB_PWD}

# Flyway config
spring.flyway.enabled=false

# Config for Manual Flyway run in integration testing
ts.flyway.user.name=${TS_FLYWAY_USER}
ts.flyway.user.pwd=${TS_FLYWAY_PWD}

ts.db.name=${TS_DB_NAME}

fdw.read.user=${FDW_READ_USER}