spring.application.name=pipeline

# DB / jOOQ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jooq.sql-dialect=POSTGRES

# The Local Cluster Connection
spring.kafka.bootstrap-servers=localhost:9092

# Consumer Settings
spring.kafka.consumer.group-id=normalization-processor-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.max-poll-records=200

spring.kafka.listener.type=batch
spring.kafka.listener.ack-mode=MANUAL

# Use the ErrorHandlingDeserializer wrapper to capture deserialization errors safely
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Producer Settings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all

# Tell the wrapper to delegate the actual work to the JsonDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust the target package structure so Jackson is permitted to instantiate your class
spring.kafka.consumer.properties.spring.json.trusted.packages=ch.swisstopo.monteis.*

spring.kafka.consumer.properties.spring.json.value.default.type=ch.swisstopo.monteis.pipeline.ingress.external.solexperts.RawSolExpertsSensorData

# Kafka Topic Configuration
app.kafka.topics.raw-solexperts=internal-raw-solexperts
app.kafka.topics.normalized=internal-normalized
app.kafka.topics.sensor-config=internal-sensor-config

# Default safe value: 1000 records per transaction
app.pipeline.reprocessing.chunk-size=1000