# Logging
logging.level.ch.swisstopo.monteis.pipeline=DEBUG

# DB Configuration (JOOQ)
spring.datasource.url=jdbc:postgresql://localhost:5433/${app.migration.timescale.dbname}
spring.datasource.username=pipeline_app
spring.datasource.password=pwd_pipeline_app

app.migration.timescale.dbname=monteis-tsdb
app.migration.timescale.url=jdbc:postgresql://localhost:5433/${app.migration.timescale.dbname}
app.migration.timescale.username=ts_flyway
app.migration.timescale.password=pwd_ts_flyway
app.migration.timescale.locations=classpath:/db/migration/timeseries

# jOOQ
spring.jooq.sql-dialect=POSTGRES

# Flyway / migration user
spring.flyway.enabled=true
spring.flyway.url=${app.migration.timescale.url}
spring.flyway.user=${app.migration.timescale.username}
spring.flyway.password=${app.migration.timescale.password}
spring.flyway.locations=${app.migration.timescale.locations}