name: Build and Push Pipeline Image

on:
  push:
    branches:
      - main
    paths:
      - 'pipeline/**/*.java'
      - 'pipeline/**/*.xml'
      - 'pom.xml'

permissions:
  contents: write # required for: git push tag
  id-token: write # required for: aws-actions/amazon-ecr-login

jobs:
  build-pipeline:
    uses: ./.github/workflows/reusable__build-push-image.yml
    with:
      service: 'pipeline'