name: Build and Push Backend Images

on:
  push:
    branches:
      - mon-93-docker-build
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/**' #todo: remove me after testing
      - '.gitignore'
      - 'webapp/**'
      - 'LICENSE'

permissions:
  contents: write
  id-token: write

jobs:
  build-core:
    uses: ./.github/workflows/reusable__build-push-image.yml
    with:
      service: 'core'

  build-pipeline:
    uses: ./.github/workflows/reusable__build-push-image.yml
    with:
      service: 'pipeline'