name: Build and Push Core API
# todo: add spec for path!
on:
  push:
    branches:
      - mon-93-docker-build

env:
  JAVA_VERSION: ${{ vars.JAVA_VERSION }}
  JAVA_DISTRIBUTION: ${{ vars.JAVA_DISTRIBUTION }}
  NODE_VERSION: ${{ vars.NODE_VERSION }}

permissions:
  contents: write # used for github tag creation
  id-token: write # used for aws auth

jobs:
  build-scan-tag:
    name: Build & Scan Core API
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Must fetch history so the bot can read the commits
          filter: blob:none

      # ---------------------------------------------------------
      # 1. DRY RUN VERSION CALCULATION
      # This looks at the commits, calculates the next tag, and stops.
      # It does NOT push the tag to GitHub.
      # ---------------------------------------------------------
      - name: Calculate Semantic Version
        id: semver
        uses: paulhatch/semantic-version@v6.0.2
        with:
          tag_prefix: "core-v"
          change_path: "core/"

      - name: Check if already tagged
        if: steps.semver.outputs.is_tagged == 'true' && steps.semver.outputs.changed == 'false'
        run: |
          echo "This commit is already tagged as ${{ steps.semver.outputs.version_tag }}. Skipping deployment."

      # aws login
      - name: Configure AWS Credentials
        if: steps.semver.outputs.is_tagged == 'false' && steps.semver.outputs.changed == 'true'
        uses: aws-actions/configure-aws-credentials@v6.2.2
        with:
          role-to-assume: ${{vars.AWS_ROLE_ECR_PUSH}}
          aws-region: ${{vars.AWS_REGION}}
      - name: Additional steps
        run: |
          # Your commands that require AWS credentials
          aws sts get-caller-identity

      # login to ecr
      - name: Login to Amazon ECR Public
        if: steps.semver.outputs.is_tagged == 'false' && steps.semver.outputs.changed == 'true'
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2.1.6

      - name: Setup Java Environment
        if: steps.semver.outputs.is_tagged == 'false' && steps.semver.outputs.changed == 'true'
        uses: ./.github/actions/setup-java-maven

      - name: Build Spring Boot Image
        if: steps.semver.outputs.is_tagged == 'false' && steps.semver.outputs.changed == 'true'
        env:
          VERSION: ${{ steps.semver.outputs.version }}
        run: |
          mvn -pl core spring-boot:build-image \
            -Dspring-boot.build-image.imageName=local-registry/core:$VERSION \
            -DskipTests

      - name: Run Trivy Image Scan
        if: steps.semver.outputs.is_tagged == 'false' && steps.semver.outputs.changed == 'true'
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'local-registry/core:${{ steps.semver.outputs.version }}'
          scan-type: 'image'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Build, tag, and push docker image to Amazon ECR Public
        if: steps.semver.outputs.is_tagged == 'false' && steps.semver.outputs.changed == 'true'
        env:
          REGISTRY: ${{ vars.AWS_ECR_REGISTRY }}
          REPOSITORY: "core"
          VERSION: ${{ steps.semver.outputs.version }}
        run: |
          # Tag the locally built image with the ECR registry path + SemVer
          docker tag local-registry/core:$VERSION ${REGISTRY}${REPOSITORY}:$VERSION
          
          # Push the tag to AWS ECR
          docker push ${REGISTRY}${REPOSITORY}:$VERSION

      # create and push github tag
      - name: Push Git Tag to GitHub
        if: steps.semver.outputs.is_tagged == 'false' && steps.semver.outputs.changed == 'true'
        env:
          TAG: ${{ steps.semver.outputs.version_tag }}
        run: |
          echo "[INFO]: Tagging commit with $TAG"
      
          # Create and push the tag
          git tag $TAG
          git push origin $TAG