name: Security Scan

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  scan:
    name: Scan Pull Request
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          cache: maven

      - name: Resolve Maven Dependencies
        run: mvn dependency:go-offline

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          version: 'v0.72.0'
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          trivyignores: '.trivyignore'