name: Test
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

env:
  TS_DB_NAME: ${{ vars.TS_DB_NAME }}
  TS_FLYWAY_USER: ${{ vars.TS_FLYWAY_USER }}
  TS_FLYWAY_PWD: ${{ vars.TS_FLYWAY_PWD }}
  META_DB_NAME: ${{ vars.META_DB_NAME }}
  META_FLYWAY_USER: ${{ vars.META_FLYWAY_USER }}
  META_FLYWAY_PWD: ${{ vars.META_FLYWAY_PWD }}

  FDW_READ_USER: ${{ vars.FDW_READ_USER }}
  PIPELINE_APP_TS_DB_USER: ${{ vars.PIPELINE_APP_TS_DB_USER}}
  PIPELINE_APP_TS_DB_PWD: ${{ vars.PIPELINE_APP_TS_DB_PWD }}
  CORE_APP_META_DB_USER: ${{ vars.CORE_APP_META_DB_USER }}
  CORE_APP_META_DB_PWD: ${{ vars.CORE_APP_META_DB_PWD }}

jobs:
  setup:
    name: Setup and Generate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          cache: maven
          cache-dependency-path: pom.xml

      - name: Generate and Compile All Classes
        run: mvn install -DskipTests

      - name: Persist Workspace
        uses: actions/upload-artifact@v7
        with:
          name: compiled-workspace
          path: .
          include-hidden-files: true

  core-unit-test:
    needs: setup
    name: Core Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v7
        with:
          name: compiled-workspace
        
      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          cache: maven
          cache-dependency-path: pom.xml

      - name: Run Core Tests
        run: mvn test -pl core -Djooq.codegen.skip=true

  core-integration-test:
    needs: setup
    name: Core Integration Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v7
        with:
          name: compiled-workspace

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          cache: maven
          cache-dependency-path: pom.xml

      - name: Run Core Tests
        run: mvn -Dskip.ut=true verify -pl core -Djooq.codegen.skip=true

  pipeline-unit-test:
    needs: setup
    name: Pipeline Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v7
        with:
          name: compiled-workspace

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          cache: maven
          cache-dependency-path: pom.xml

      - name: Run Pipeline Tests
        run: mvn test -pl pipeline -Djooq.codegen.skip=true

  pipeline-integration-test:
    needs: setup
    name: Pipeline Integration Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          cache: maven
          cache-dependency-path: pom.xml

      - name: Download Workspace
        uses: actions/download-artifact@v7
        with:
          name: compiled-workspace
          path: ..

      - name: Run Pipeline Tests
        run: mvn -Dskip.ut=true verify -pl pipeline -Djooq.codegen.skip=true

  webapp-test:
    name: Webapp Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: maven
          cache-dependency-path: pom.xml

      - name: Install Dependencies and generate Sources
        run: mvn clean install -DskipTests -Dopenapi.codegen.skip=false

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: webapp/package.json

      - name: Set up Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: webapp/pnpm-lock.yaml

      - name: Install Node Modules and Playwright
        run: |
          cd webapp
          pnpm install
          pnpm exec playwright install
          pnpm run generate-api

      - name: Run Webapp Tests
        run: |
          cd webapp
          pnpm vitest --browser.headless=true