name: testing.yml
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

env:
  TS_DB_NAME: ${{ vars.TS_DB_NAME }}
  TS_FLYWAY_USER: ${{ vars.TS_FLYWAY_USER }}
  TS_FLYWAY_PWD: ${{ vars.TS_FLYWAY_PWD }}
  META_DB_NAME: ${{ vars.META_DB_NAME }}
  META_FLYWAY_USER: ${{ vars.META_FLYWAY_USER }}
  META_FLYWAY_PWD: ${{ vars.META_FLYWAY_PWD }}

  FDW_READ_USER: ${{ vars.FDW_READ_USER }}
  PIPELINE_APP_TS_DB_USER: ${{ vars.PIPELINE_APP_TS_DB_USER}}
  PIPELINE_APP_TS_DB_PWD: ${{ vars.PIPELINE_APP_TS_DB_PWD }}
  CORE_APP_META_DB_USER: ${{ vars.CORE_APP_META_DB_USER }}
  CORE_APP_META_DB_PWD: ${{ vars.CORE_APP_META_DB_PWD }}

jobs:
  build:
    name: Build backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: maven
          cache-dependency-path: pom.xml

      - name: Install Dependencies and generate Sources
        run: mvn clean install -DskipTests -Dopenapi.codegen.skip=false

      - name: Upload JAR
        uses: actions/upload-artifact@v7
        with:
          name: backend-jar
          path: "**/target/*.jar"

  core-test:
    needs: [ build ]
    name: Core Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          cache: maven
          cache-dependency-path: pom.xml

      - name: Download build
        uses: actions/download-artifact@v7
        with:
          name: backend-jar
          path: target

      - name: Create .env file for tests
        env:
          ENV_CONTENTS: ${{ secrets.TEST_ENV_FILE_CONTENTS }}
        run: |
          echo "$ENV_CONTENTS" > .env

      - name: Run Core Tests
        run: mvn verify -pl core -am

  pipeline-test:
    needs: [ build ]
    name: Pipeline Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          cache: maven
          cache-dependency-path: pom.xml

      - name: Run Pipeline Tests
        run: mvn verify -pl pipeline -am

  webapp-test:
    needs: [build]
    name: Webapp Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Download build
        uses: actions/download-artifact@v7
        with:
          name: backend-jar
          path: target

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: webapp/package.json
          
      - name: Download .env artifact
        uses: actions/download-artifact@v7
        with:
          name: shared-env-file

      - name: Set up Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: webapp/pnpm-lock.yaml

      - name: Run Webapp Tests
        run: |
          java -jar target/*.jar &
          cd webapp
          pnpm install
          pnpm test